on: [push]

name: Run unit tests

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Get to the right branch
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4

    - name: Restore the node modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Update NPM packages
      run: npm i --include=dev

    - name: Run tests
      run: npm run test
